CREATE DATABASE IF NOT EXISTS media_storage DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;

CREATE TABLE IF NOT EXISTS media_storage.books (
  id INT NOT NULL AUTO_INCREMENT,
  name VARCHAR(45) NOT NULL,
  status ENUM('WANT_TO_READ', 'READ', 'AM_READING') NOT NULL,
  PRIMARY KEY (id));

CREATE TABLE IF NOT EXISTS media_storage.movies (
  id INT NOT NULL AUTO_INCREMENT,
  name VARCHAR(45) NOT NULL,
  status ENUM('WANT_TO_WATCH', 'WATCHED', 'AM_WATCHING') NOT NULL,
  PRIMARY KEY (id));

CREATE TABLE IF NOT EXISTS media_storage.musics (
  id INT NOT NULL AUTO_INCREMENT,
  name VARCHAR(45) NOT NULL,
  status ENUM('WANT_TO_LISTEN', 'LISTENED', 'AM_LISTENING') NOT NULL,
  PRIMARY KEY (id));